name = "crdt"
description = "CRDT library for Ada/SPARK"
version = "1.1.0"

authors = ["bladeacer"]
maintainers = ["bladeacer <wg.nick.exe@gmail.com>"]
maintainers-logins = ["bladeacer"]
licenses = "MIT"
website = "https://github.com/bladeacer/ada_crdt"
tags = ["crdt", "spark", "ada"]

