name = "ada_crdt"
description = "CRDT library for Ada/SPARK"
version = "0.1.0-dev"
licenses = "MIT"
authors = ["bladeacer"]
maintainers = ["bladeacer <wg.nick.exe@gmail.com>"]
maintainers-logins = ["bladeacer"]
website = "https://codeberg.org/bladeacer/Ada_CRDT"
tags = ["crdt", "spark", "ada", "library"]
auto-gpr-with = false

[origin]
url = "git+https://codeberg.org/bladeacer/Ada_CRDT.git"
commit = "cd24394a64c101ed0fa3592386ac53c1d529c3cf"
