name = "ada_crdt"
description = "CRDT library for Ada/SPARK"
version = "0.2.0"
licenses = "MIT"
authors = ["bladeacer"]
maintainers = ["bladeacer <wg.nick.exe@gmail.com>"]
maintainers-logins = ["bladeacer"]
website = "https://github.com/bladeacer/ada_crdt"
tags = ["crdt", "spark", "ada", "library"]
auto-gpr-with = false

[origin]
url = "git+https://github.com/bladeacer/ada_crdt.git"
commit = "f53d561cd72611cc603fb147c254e78bdb4b4e00"
