/* Configuration for crdt generated by Alire */
#ifndef CRDT_CONFIG_H
#define CRDT_CONFIG_H

#define CRATE_VERSION "1.5.0"
#define CRATE_NAME "crdt"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "arch"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
